######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 16 16:41:30 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += gtrans.h
SOURCES += gtrans.cpp main.cpp
